### ISSUE TITLE
Update to version 3.11

### ISSUE THREAD

**Issue by eylenburg** [flathub/org.netsurf_browser.NetSurf#4]
Netsurf 3.11 was released on 28/12/23 after more than 3.5 years of waiting :)

**Comment by ivanov17** [comment]
PR https://github.com/flathub/org.netsurf_browser.NetSurf/pull/5

**Comment by ivanov17** [comment]
Netsurf 3.11 [is now available](https://flathub.org/apps/org.netsurf_browser.NetSurf) on Flathub.

@eylenburg You can close this issue.
